Add calculation functionality
piero-vic/math-magicians pull request #3
Opened 2021-11-24 22:16 UTC by piero-vic

# Add calculation functionality
- Add `calculate.js` and `operate.js`.
- Create Button component.
- Add functionality for calculations.

2021-11-24 22:22 UTC, bimbolabuari requested changes
Hi @piero-vic, 

You have done a good job so far 🚀  

## Highlights 🎉
- Copied the files calculate.js and operate.js into a logic/ directory in your project. ✊
- Imported the files in your Calculator component. 🚀
- Implemented the event handlers. 🎉
- Used state and props 👍

There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

2021-11-24 22:22 UTC, bimbolabuari commented on src/components/Button.js
> +// eslint-disable-next-line react/prefer-stateless-function
Kindly remove this disabled linter, linting improves readability, removes errors. 👍

Please check for other occurrences 🙂

2021-11-24 22:29 UTC, piero-vic commented on src/components/Button.js
> +// eslint-disable-next-line react/prefer-stateless-function
Hi. One of the requirements for the previous section was to implement all components as class-based. Removing the linters will impede me to to use class-based components. Should I just change them?

2021-11-25 15:11 UTC, od-c0d3r commented
Asslam Alaikum @piero-vic  ,😊

Hi👋🏽, Your project is complete!  There is nothing else to say other than... it's time to merge it 😎 

# Congratulations! 🎉 

Happy coding!👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 15:11 UTC, merged